name: Generate ASCII Artwork

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "Github Actions test"

            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Install cowsay
              run: sudo apt install cowsay -y

            - name: Execute cowsay
              run: cowsay -f dragon "Thar be dragons" >> dragon.txt

            - name: cat dragon.txt
              run: cat dragon.txt

            - name: PWD
              run: pwd