name: Generate ASCII Artwork

on: push

jobs:
    generate_ascii_art:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "Github Actions test"

            - name: Checkout repo
              uses: actions/checkout@v4

            - name: ls files
              run: ls -ltra
            
            - name: Execute script
              run: |
                chmod u+x ascii-script.sh
                ./ascii-script.sh

            - name: PWD
              run: pwd